Vagrant.configure('2') do |config|
  config.ssh.username = 'tester'
  config.ssh.private_key_path = 'test_id_rsa'

  config.vm.synced_folder '.', '/tmp/test', type: "rsync",
    rsync__exclude: ['cookbooks/', 'scripts/'],
    rsync__args: ['--verbose', '--archive', '--delete', '-z', '--progress'],
    rsync__auto: true

  config.vm.provider :digital_ocean do |provider, override|
    override.vm.box = 'digital_ocean'
    override.vm.box_url = "https://github.com/smdahlen/vagrant-digitalocean/raw/master/box/digital_ocean.box"
    provider.token = ENV['DO_TOKEN']
    provider.ssh_key_name = 'Test Key'
  end

  config.vm.provision :shell, :path => 'scripts/provision.sh'

  config.vm.define :ubuntu do |ubuntu|
    ubuntu.vm.provider :digital_ocean do |provider|
      provider.image = 'ubuntu-14-04-x64'
    end
  end

  config.vm.define :centos do |centos|
    centos.vm.provider :digital_ocean do |provider|
      provider.image = 'centos-6-5-x64'
    end
  end
  
  config.vm.define :coreos do |coreos|
    coreos.vm.provider :digital_ocean do |provider|
      provider.image                = 'coreos-alpha'
      provider.root_username        = 'core'
      provider.setup                = false
      provider.private_networking   = true
      provider.user_data            = File.read('user-data.yml').gsub(/@SSH_PUBKEY@/,File.read('test_id_rsa.pub'))
      provider.domain               = 'test.com'
    end
  end
end
